-- 11 - Para cada fabricante, retorne: NOME_FABRICANTE, total de carros vendidos, valor total vendido e ticket médio por venda; ordene por valor total vendido desc.

SELECT t1.NOME_FABRICANTE,
       COUNT(t3.COD_CARRO) AS TOTAL_CARROS_VENDIDOS,
       COALESCE(SUM(t4.PRECO_VENDA), 0) AS VALOR_TOTAL_VENDIDO,
       COALESCE(AVG(t4.PRECO_VENDA), 0) AS TICKET_MEDIO_POR_CARRO
FROM TB_FABRICANTE t1
LEFT JOIN TB_MODELO t2 
ON t1.COD_FABRICANTE = t2.COD_FABRICANTE
LEFT JOIN TB_CARRO t3 
ON t2.COD_MODELO = t3.COD_MODELO AND t3.STATUS = 'VENDIDO'
LEFT JOIN TB_VENDA_ITEM t4
ON t3.COD_CARRO = t4.COD_CARRO
GROUP BY t1.NOME_FABRICANTE
ORDER BY VALOR_TOTAL_VENDIDO DESC;

-- 12 - Retorne o ranking de vendedores por faturamento total no período de 2025-02-01 a 2025-02-28, 
-- exibindo: COD_VENDEDOR, NOME_VENDEDOR, TOTAL_VENDIDO, QTD_VENDAS, TICKET_MEDIO, e a posição no ranking.

SELECT t1.COD_VENDEDOR,
       t1.NOME_VENDEDOR,
       SUM(t2.TOTAL_VENDA) AS TOTAL_VENDIDO,
       COUNT(t2.COD_VENDA) AS QTD_VENDAS,
       ROW_NUMBER() OVER (PARTITION BY 1 ORDER BY SUM(t2.TOTAL_VENDA) DESC) AS RANKING
FROM TB_VENDEDOR t1
LEFT JOIN TB_VENDA t2
ON t1.COD_VENDEDOR = t2.COD_VENDEDOR
AND DT_VENDA >= '2025-02-01'
AND DT_VENDA < '2025-03-01'
GROUP BY t1.COD_VENDEDOR
ORDER BY RANKING;

-- 13 - Identifique possíveis inconsistências entre TB_VENDA.TOTAL_VENDA 
-- e a soma de TB_VENDA_ITEM.TOTAL_ITEM por venda. 
-- Retorne somente as vendas com divergência, exibindo: 
-- COD_VENDA, TOTAL_VENDA, SOMA_ITENS, DIFERENCA.

SELECT 
    t1.COD_VENDA,
    t1.TOTAL_VENDA,
    t2.SOMA_ITENS,
    ROUND(t1.TOTAL_VENDA - t2.SOMA_ITENS, 2) AS DIFERENCA
FROM TB_VENDA t1
INNER JOIN (
    SELECT 
        COD_VENDA,
        SUM(TOTAL_ITEM) AS SOMA_ITENS
    FROM TB_VENDA_ITEM
    GROUP BY COD_VENDA
) t2 ON t1.COD_VENDA = t2.COD_VENDA
WHERE ROUND(t1.TOTAL_VENDA - t2.SOMA_ITENS, 2) != 0;

WITH tb_venda_soma AS (
    SELECT 
        COD_VENDA,
        SUM(TOTAL_ITEM) AS SOMA_ITENS
    FROM TB_VENDA_ITEM
    GROUP BY COD_VENDA
)

SELECT 
    t1.COD_VENDA,
    t1.TOTAL_VENDA,
    t2.SOMA_ITENS,
    ROUND(t1.TOTAL_VENDA - t2.SOMA_ITENS, 2) AS DIFERENCA
FROM TB_VENDA t1
INNER JOIN tb_venda_soma t2 ON t1.COD_VENDA = t2.COD_VENDA
WHERE ROUND(t1.TOTAL_VENDA - t2.SOMA_ITENS, 2) != 0;


-- 14 - Para cada loja, calcule a participação (%) de carros importados 
-- (FL_NACIONAL = 'N' no modelo) sobre o total de carros vendidos da loja, 
-- exibindo: COD_LOJA, NOME_LOJA, QTD_VENDIDOS, QTD_IMPORTADOS, PCT_IMPORTADOS.

SELECT T1.COD_LOJA,
       T1.NOME_LOJA,
       COUNT(*) AS QTD_VENDIDOS,
       COUNT(CASE WHEN T3.FL_NACIONAL = 'N' THEN 1 END) AS QTD_IMPORTADOS,
       ROUND(
        COUNT(CASE WHEN T3.FL_NACIONAL = 'N' THEN 1 END) * 100.0 / 
            NULLIF(COUNT(T2.COD_CARRO), 0), 
            2
        ) AS PCT_IMPORTADOS
FROM TB_LOJA T1
LEFT JOIN TB_CARRO T2 ON T1.COD_LOJA = T2.COD_LOJA AND T2.STATUS = 'VENDIDO'
LEFT JOIN TB_MODELO T3 ON T2.COD_MODELO = T3.COD_MODELO
GROUP BY T1.COD_LOJA, T1.NOME_LOJA;


-- 15 - Retorne, para cada segmento de modelo (SEGMENTO), o modelo líder em faturamento 
-- (maior soma de TOTAL_ITEM) e o respectivo faturamento, 
-- exibindo: SEGMENTO, COD_MODELO, NOME_MODELO, FATURAMENTO_MODELO.

SELECT 
    SEGMENTO,
    COD_MODELO,
    NOME_MODELO,
    FATURAMENTO_MODELO
FROM (
    SELECT 
        T1.SEGMENTO,
        T1.COD_MODELO,
        T1.NOME_MODELO,
        SUM(T3.TOTAL_ITEM) AS FATURAMENTO_MODELO,
        ROW_NUMBER() OVER (PARTITION BY T1.SEGMENTO ORDER BY SUM(T3.TOTAL_ITEM) DESC) AS rank
    FROM TB_MODELO T1
    INNER JOIN TB_CARRO T2 ON T1.COD_MODELO = T2.COD_MODELO
    INNER JOIN TB_VENDA_ITEM T3 ON T2.COD_CARRO = T3.COD_CARRO
    GROUP BY T1.SEGMENTO, T1.COD_MODELO, T1.NOME_MODELO
) 
WHERE rank = 1
ORDER BY SEGMENTO;


