-- 1 - Liste todos os clientes cadastrados, mostrando: COD_CLIENTE, NOME_CLIENTE, CPF, CIDADE, ESTADO, DT_CADASTRO.

SELECT COD_CLIENTE, NOME_CLIENTE, CPF, CIDADE, ESTADO, DT_CADASTRO
FROM TB_CLIENTE;

-- 2 - Liste todos os carros com status EM_ESTOQUE, mostrando: COD_CARRO, VIN, COD_MODELO, ANO_FABRICACAO, KM, PRECO_TABELA, COD_LOJA.

SELECT COD_CARRO, VIN, COD_MODELO, ANO_FABRICACAO, KM, PRECO_TABELA, COD_LOJA
FROM TB_CARRO
WHERE STATUS = 'EM_ESTOQUE';


-- 3 - Retorne os vendedores da loja COD_LOJA numero 2, mostrando: COD_VENDEDOR, NOME_VENDEDOR, EMAIL, DT_ADMISSAO, COMISSAO_PCT.

SELECT COD_VENDEDOR, NOME_VENDEDOR, EMAIL, DT_ADMISSAO, COMISSAO_PCT
FROM TB_VENDEDOR
WHERE COD_LOJA = 2;


-- 4 - Mostre todos os modelos nacionais com: COD_MODELO, NOME_MODELO, SEGMENTO, TIPO_COMBUSTIVEL, ANO_INICIO.

SELECT COD_MODELO, NOME_MODELO, SEGMENTO, TIPO_COMBUSTIVEL, ANO_INICIO
FROM TB_MODELO
WHERE FL_NACIONAL = 'S';

-- 5 - Liste as vendas realizadas em fevereiro/2025, mostrando: COD_VENDA, DT_VENDA, FORMA_PAGTO, TOTAL_VENDA, COD_CLIENTE.

SELECT COD_VENDA, DT_VENDA, FORMA_PAGTO, TOTAL_VENDA, COD_CLIENTE
FROM TB_VENDA
WHERE DT_VENDA >= '2025-02-01' AND DT_VENDA < '2025-03-01';

