
-- 6 - Liste cada carro (unidade) com seu modelo e fabricante, exibindo: COD_CARRO, VIN, NOME_MODELO, NOME_FABRICANTE, STATUS.

SELECT t1.COD_CARRO, t1.VIN, t2.NOME_MODELO, t3.NOME_FABRICANTE, t1.STATUS
FROM TB_CARRO AS t1
LEFT JOIN TB_MODELO AS t2
ON t1.COD_MODELO = t2.COD_MODELO
LEFT JOIN TB_FABRICANTE AS t3
ON t2.COD_FABRICANTE = t3.COD_FABRICANTE;

-- 7 - Retorne o total de carros por status (EM_ESTOQUE, RESERVADO, VENDIDO) e ordene do maior para o menor.

SELECT STATUS, COUNT(*) AS QUANTIDADE
FROM TB_CARRO
GROUP BY STATUS
ORDER BY QUANTIDADE DESC;

-- Esta tudo como vendido, näo entendi o porque do exercicio

-- 8 - Para cada loja, mostre: COD_LOJA, NOME_LOJA, CIDADE, ESTADO e a quantidade de vendedores na loja.

SELECT t1.COD_LOJA, t1.NOME_LOJA, t1.CIDADE, t1.ESTADO, COUNT(t2.COD_VENDEDOR) AS TOTAL_VENDEDORES
FROM TB_LOJA AS t1
LEFT JOIN TB_VENDEDOR AS t2
ON t1.COD_LOJA = t2.COD_LOJA
GROUP BY t1.COD_LOJA, t1.NOME_LOJA, t1.CIDADE, t1.ESTADO;

-- 9 - Retorne as vendas com dados do cliente e do vendedor, exibindo: COD_VENDA, DT_VENDA, NOME_CLIENTE, NOME_VENDEDOR, FORMA_PAGTO, TOTAL_VENDA.

SELECT t1.COD_VENDA, t1.DT_VENDA, t3.NOME_CLIENTE, t2.NOME_VENDEDOR, t1.FORMA_PAGTO, t1.TOTAL_VENDA
FROM TB_VENDA AS t1
LEFT JOIN TB_VENDEDOR AS t2
ON t1.COD_VENDEDOR = t2.COD_VENDEDOR
LEFT JOIN TB_CLIENTE AS t3
ON t1.COD_CLIENTE = t3.COD_CLIENTE;


-- 10 - Retorne os 3 modelos mais vendidos (por quantidade de carros vendidos), mostrando: COD_MODELO, NOME_MODELO, QTD_VENDIDA.

SELECT t3.COD_MODELO, t3.NOME_MODELO, COUNT(DISTINCT t1.COD_CARRO) AS QTD_VENDIDA
FROM TB_VENDA_ITEM AS t1
LEFT JOIN TB_CARRO AS t2
ON t1.COD_CARRO = t2.COD_CARRO
LEFT JOIN TB_MODELO AS t3
ON t2.COD_MODELO = t3.COD_MODELO
GROUP BY t3.COD_MODELO
ORDER BY QTD_VENDIDA DESC
LIMIT 3;

